### ISSUE TITLE
Authentication doesn't work when there are groups with backslashes in them

### ISSUE THREAD

**Issue by josefsabl** [foglcz/ldap-authenticator#2]
Can't really post full Tracy output here as it is full of personal info. But here is the screen http://screenpresso.com/=rrg1f

The problem is simple, when there is a group with backslash in its name the search fails as it is not properly escaped. This naive fix corrected the problem.

In GroupsLoader.php

```
	protected function getGroupMemberOf(Manager $ldap, $groupDn)
	{
		$groupDn = addslashes($groupDn); //FIX
		return $ldap->search(null, str_replace(':group:', $groupDn, self::$GroupMemberOfLookup));
	}
```

**Comment by foglcz** [comment]
Interesting, good catch! I can play around with this somewhere during the weekend, but can you PR in the meantime? Would like to merge into master asap..

**Comment by foglcz** [comment]
Also thinking about this one.. Backslash would be there only when you have trust between domains, right? That would mean that:

1) your user is, say, `contoso\username`
2) he's a member of `contoso\groupA` (<- this works without fix)
3) he's also a member of `client\groupB` (<- client is a separate, trusted domain, which doesn't work)

How do you handle authorization for the client's members then? Based on the baseDN search path?

If you'd be more comfortable to move this discussion into private channel, shoot me an email to `ptacek.pavel@gmail.com` , I'm interested in your deployment if not strictly confidential. Because we might be able to carry out tests of LdapAuthenticator on the two domains without having to set it up ourselves ;)

Let me know.
(also, if you PR the fix, you'll be able to reference it from your composer.json. I'll release the fix this weekend, really want to play around with the multi domain membership - one feature I did not think about!)

**Comment by josefsabl** [comment]
I will not post pull request as addslashes is not the correct function to fix this. Ldap_escape should be used but it relies on PHP 5.6 and would break backwards compatibility of this library.
